[build-system]
requires = [
    # Support for setuptools.build_meta was added in 36.6.0 by
    # https://github.com/pypa/setuptools/pull/1143
    "setuptools>=36.6.0",
    # For building wheels
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "lunch-voting"
requires-python = ">=3.13"
description = "Lunch Voting API"
dynamic = ["version", "readme"]
dependencies = [
    "fastapi[standard] == 0.115.12",
    "SQLAlchemy == 2.0.41",
    "PyJWT == 2.10.1",
    "bcrypt == 4.3.0",
    "pydantic-settings == 2.9.1",
    "python-dotenv == 1.1.0",
]

[project.optional-dependencies]
test = [
    "build == 1.2.2",
    "pytest == 8.4.0",
    "pytest-cov == 6.1.1",
    "pytest-asyncio == 1.0.0",
]

lint = [
    "mypy == 1.15.0",
    "ruff == 0.11.10",
    "pre-commit == 4.2.0",
]

[options]
package_dir = ["src"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]

[tool.setuptools.dynamic]
version = {attr = "app.__version__"}
readme = {file = ["README.md"]}


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov --cov-report html --cov-report term -vvvv --import-mode=importlib"
pythonpath = ["src"]
testpaths = ["tests"]


[tool.mypy]
exclude = ["build"]

[tool.ruff]
include = ["src/*", "tests/*"]
exclude = ["__pycache__"]
line-length = 100
